#ifndef GUARD_CONSTANTS_FACTORY_BOSS_H
#define GUARD_CONSTANTS_FACTORY_BOSS_H

#define FACTORY_BOSS_NONE     0
// Hoenn Gym Leaders (no Tate & Liza yet, since they are a double battle only)
#define FACTORY_BOSS_ROXANNE  1
#define FACTORY_BOSS_BRAWLY   2
#define FACTORY_BOSS_WATTSON  3
#define FACTORY_BOSS_FLANNERY 4
#define FACTORY_BOSS_NORMAN   5
#define FACTORY_BOSS_WINONA   6
#define FACTORY_BOSS_JUAN     7

// Other bosses
#define FACTORY_BOSS_STEVEN   8
#define FACTORY_BOSS_WALLY    9
#define FACTORY_BOSS_RED      10
#define FACTORY_BOSS_BLUE     11
#define FACTORY_BOSS_CYNTHIA  12
#define FACTORY_BOSS_COUNT    13

enum FactoryBossAcePolicy
{
    FACTORY_BOSS_ACE_NONE,
    FACTORY_BOSS_ACE_SPECIES_ANCHOR_LAST,
    FACTORY_BOSS_ACE_SPECIES_ANCHOR_FIRST,
};

#endif // GUARD_CONSTANTS_FACTORY_BOSS_H
