sText_StevenPreBattleCall::
# 11 "data/text/factory_boss_texts.pory"
	.string "Report from the floor:\n"
	.string "STEVEN has entered the arena.\p"
	.string "He says he's ready whenever you are.$"

sText_StevenBattleRoomPrompt::
# 18 "data/text/factory_boss_texts.pory"
	.string "So we meet again, {PLAYER}!$"

sText_StevenBattleIntro::
# 22 "data/text/factory_boss_texts.pory"
	.string "I heard you've done very well in here.\n"
	.string "I would expect nothing less from you!\p"
	.string "Battles fought with borrowed teams\n"
	.string "demand even sharper judgment.\p"
	.string "But I don't believe you've had\n"
	.string "a real test in the FACTORY yet.\p"
	.string "I am on a different level to the\n"
	.string "TRAINERS in this place,\l"
	.string "without exception.\p"
	.string "Let's see how you deal with a real test!\n"
	.string "I'm ready. Now face me, {PLAYER}!$"

sText_StevenLastMonSlide::
# 40 "data/text/factory_boss_texts.pory"
	.string "You're forcing me into a corner,\n"
	.string "but I'm just getting started!$"

sText_StevenLastMonLowHpSlide::
# 45 "data/text/factory_boss_texts.pory"
	.string "Outstanding... Here we go!\n"
	.string "I'll answer with everything I've got!$"

sText_StevenBattlePostWin::
# 50 "data/text/factory_boss_texts.pory"
	.string "Excellent battle.\n"
	.string "You stayed calm, read the battlefield,\l"
	.string "and made every turn count.$"

sText_StevenBattleSpeechPlayerWon::
# 56 "data/text/factory_boss_texts.pory"
	.string "{PLAYER}!\n"
	.string "You are truly a remarkable TRAINER...$"

sText_StevenBattleSpeechPlayerLost::
# 61 "data/text/factory_boss_texts.pory"
	.string "Ha! Not on my watch!$"

sText_DebugBossName_Steven::
# 65 "data/text/factory_boss_texts.pory"
	.string "Steven$"

sText_WallyPreBattleCall::
# 72 "data/text/factory_boss_texts.pory"
	.string "A call just came in from WALLY.\n"
	.string "He's waiting in the arena for you.$"

sText_WallyBattleRoomPrompt::
# 77 "data/text/factory_boss_texts.pory"
	.string "I'm ready... Please come forward!$"

sText_WallyBattleIntro::
# 81 "data/text/factory_boss_texts.pory"
	.string "It's me, WALLY.\p"
	.string "Did you ever believe, back when\n"
	.string "we first met, that I would become\l"
	.string "an elite TRAINER?\p"
	.string "No one did.\n"
	.string "No one apart from me.\p"
	.string "I've been training hard so I can\n"
	.string "stand here with confidence.\p"
	.string "I've been on such a journey with my\n"
	.string "POKéMON. I've traveled through many\l"
	.string "regions and battled my way through\l"
	.string "all of them.\p"
	.string "Don't you see?\n"
	.string "Fate has led me here, to battle\l"
	.string "against you, {PLAYER}.\p"
	.string "This time, I really think things\n"
	.string "will go my way.\p"
	.string "I haven't come all this way just\n"
	.string "to lose again!\p"
	.string "Let's do this!$"

sText_WallyLastMonSlide::
# 112 "data/text/factory_boss_texts.pory"
	.string "Here we go, {B_OPPONENT_MON1_NAME}!\n"
	.string "Don't let me down now!$"

sText_WallyLastMonLowHpSlide::
# 117 "data/text/factory_boss_texts.pory"
	.string "Not again...\n"
	.string "I won't lose again!$"

sText_WallyBattlePostWin::
# 122 "data/text/factory_boss_texts.pory"
	.string "That was amazing...\p"
	.string "Battling you teaches me something\n"
	.string "new every time.$"

sText_WallyBattleSpeechPlayerWon::
# 129 "data/text/factory_boss_texts.pory"
	.string "I gave it everything... But like\n"
	.string "always, you were one step ahead.$"

sText_WallyBattleSpeechPlayerLost::
# 134 "data/text/factory_boss_texts.pory"
	.string "I did it...!\n"
	.string "I've gotten so much stronger!$"

sText_DebugBossName_Wally::
# 139 "data/text/factory_boss_texts.pory"
	.string "Wally$"

sText_RoxannePreBattleCall::
# 147 "data/text/factory_boss_texts.pory"
	.string "Report from the floor:\n"
	.string "ROXANNE has entered the arena.\p"
	.string "She says she's ready whenever you are.$"

sText_RoxanneBattleRoomPrompt::
# 154 "data/text/factory_boss_texts.pory"
	.string "It's been a while, {PLAYER}!$"

sText_RoxanneBattleIntro::
# 158 "data/text/factory_boss_texts.pory"
	.string "I'm so glad to see you again.\n"
	.string "I'm sure we've had many, many\l"
	.string "battles since we've last met.\p"
	.string "I remember first facing you\n"
	.string "not long after you started your\l"
	.string "journey! Now look at\l"
	.string "everything you've achieved.\p"
	.string "Would you kindly demonstrate how\n"
	.string "you battle, and with what POKéMON?$"

sText_RoxanneLastMonSlide::
# 172 "data/text/factory_boss_texts.pory"
	.string "Oh wow!\n"
	.string "I didn't know you were quite this strong.$"

sText_RoxanneLastMonLowHpSlide::
# 177 "data/text/factory_boss_texts.pory"
	.string "This has been a great lesson!$"

sText_RoxanneBattlePostWin::
# 181 "data/text/factory_boss_texts.pory"
	.string "I still have much to learn when it\n"
	.string "comes to battling POKéMON. But\l"
	.string "that only makes me love battling more!$"

sText_RoxanneBattleSpeechPlayerWon::
# 187 "data/text/factory_boss_texts.pory"
	.string "I learned lots from our battle.$"

sText_RoxanneBattleSpeechPlayerLost::
# 191 "data/text/factory_boss_texts.pory"
	.string "Back to class with you!$"

sText_DebugBossName_Roxanne::
# 195 "data/text/factory_boss_texts.pory"
	.string "Roxanne$"

sText_BrawlyPreBattleCall::
# 203 "data/text/factory_boss_texts.pory"
	.string "BRAWLY is ready to throw down!$"

sText_BrawlyBattleRoomPrompt::
# 207 "data/text/factory_boss_texts.pory"
	.string "Hey, hurry up!$"

sText_BrawlyBattleIntro::
# 211 "data/text/factory_boss_texts.pory"
	.string "I haven't seen you in a while,\n"
	.string "{PLAYER}!\p"
	.string "Where have I been? Well,\n"
	.string "I've travelled the seas of HOENN\l"
	.string "and beyond.\p"
	.string "I've learned first hand how\n"
	.string "you need to be tough to survive\l"
	.string "in this world.\p"
	.string "Do you have what it takes to\n"
	.string "beat me this time?\p"
	.string "I'd like to see you try!$"

sText_BrawlyLastMonSlide::
# 229 "data/text/factory_boss_texts.pory"
	.string "Come on, {B_OPPONENT_MON1_NAME}!\n"
	.string "Lend me your strength.$"

sText_BrawlyLastMonLowHpSlide::
# 234 "data/text/factory_boss_texts.pory"
	.string "I've been raised in the rough seas!\n"
	.string "I can handle anything.$"

sText_BrawlyBattlePostWin::
# 239 "data/text/factory_boss_texts.pory"
	.string "Argh...\n"
	.string "I thought I had you beat there!$"

sText_BrawlyBattleSpeechPlayerWon::
# 244 "data/text/factory_boss_texts.pory"
	.string "Whoa! You made a much bigger\n"
	.string "splash than I expected$"

sText_BrawlyBattleSpeechPlayerLost::
# 249 "data/text/factory_boss_texts.pory"
	.string "Wow! I swamped you again!$"

sText_DebugBossName_Brawly::
# 253 "data/text/factory_boss_texts.pory"
	.string "Brawly$"

sText_WattsonPreBattleCall::
# 261 "data/text/factory_boss_texts.pory"
	.string "WATTSON is ready to face you!$"

sText_WattsonBattleRoomPrompt::
# 265 "data/text/factory_boss_texts.pory"
	.string "Hello there!$"

sText_WattsonBattleIntro::
# 269 "data/text/factory_boss_texts.pory"
	.string "I haven't seen you in a while,\n"
	.string "{PLAYER}!\p"
	.string "I never forget a face. I remember\n"
	.string "when you came to the gym in MAUVILLE,\l"
	.string "before it became the CITY that it\l"
	.string "is today.\p"
	.string "I achieved my dreams building that CITY.\n"
	.string "In that time, you became the\l"
	.string "POKéMON LEAGUE CHAMPION.\p"
	.string "I knew you were a special TRAINER\n"
	.string "after our first battle.\p"
	.string "And now you've gone and defeated\n"
	.string "the FACTORY HEAD!\p"
	.string "Ah, I'm old now, but I can still fight.\p"
	.string "Give me one last electrifying battle!$"

sText_WattsonLastMonSlide::
# 293 "data/text/factory_boss_texts.pory"
	.string "I will electrify you with my POKémon!\n"
	.string "Go, {B_OPPONENT_MON1_NAME}!$"

sText_WattsonLastMonLowHpSlide::
# 298 "data/text/factory_boss_texts.pory"
	.string "I've been around the block long\n"
	.string "enough to know I can still win this one.$"

sText_WattsonBattlePostWin::
# 303 "data/text/factory_boss_texts.pory"
	.string "Oof...\n"
	.string "Our batteries ran dry.$"

sText_WattsonBattleSpeechPlayerWon::
# 308 "data/text/factory_boss_texts.pory"
	.string "You sure gave me shock!\n"
	.string "Well played.$"

sText_WattsonBattleSpeechPlayerLost::
# 313 "data/text/factory_boss_texts.pory"
	.string "Wahahahaha!\n"
	.string "Well, I won!$"

sText_DebugBossName_Wattson::
# 318 "data/text/factory_boss_texts.pory"
	.string "Wattson$"

sText_FlanneryPreBattleCall::
# 326 "data/text/factory_boss_texts.pory"
	.string "FLANNERY has a score to settle with you!$"

sText_FlanneryBattleRoomPrompt::
# 330 "data/text/factory_boss_texts.pory"
	.string "Hey there, {PLAYER}!$"

sText_FlanneryBattleIntro::
# 334 "data/text/factory_boss_texts.pory"
	.string "It's so good to see how far\n"
	.string "you've come.\p"
	.string "I've also been on a journey of my\n"
	.string "own.\p"
	.string "I remember how immature I was when\n"
	.string "you first came to the LAVARIDGE GYM.\p"
	.string "I had only recently become a GYM LEADER,\n"
	.string "so I was still getting used to my\l"
	.string "duties.\p"
	.string "Since then, I've become much more\n"
	.string "grown up. I discovered who I really\l"
	.string "am, instead of trying to be someone\l"
	.string "that I'm not.\p"
	.string "Now let's have some fun!\n"
	.string "Get ready to feel the heat!$"

sText_FlanneryLastMonSlide::
# 357 "data/text/factory_boss_texts.pory"
	.string "Burn em' alive, {B_OPPONENT_MON1_NAME}!$"

sText_FlanneryLastMonLowHpSlide::
# 361 "data/text/factory_boss_texts.pory"
	.string "Oh no! Hang in there, {B_OPPONENT_MON1_NAME}!$"

sText_FlanneryBattlePostWin::
# 365 "data/text/factory_boss_texts.pory"
	.string "Losing a battle isn't going to deflate me.\n"
	.string "I love POKéMON, and I love to battle!$"

sText_FlanneryBattleSpeechPlayerWon::
# 370 "data/text/factory_boss_texts.pory"
	.string "You did it again!\n"
	.string "One day I'll be as strong as you!$"

sText_FlanneryBattleSpeechPlayerLost::
# 375 "data/text/factory_boss_texts.pory"
	.string "I won!\n"
	.string "I guess my well-honed moves worked.$"

sText_DebugBossName_Flannery::
# 380 "data/text/factory_boss_texts.pory"
	.string "Flannery$"

sText_NormanPreBattleCall::
# 387 "data/text/factory_boss_texts.pory"
	.string "Your father NORMAN is in the building\n"
	.string "and looking fired up!$"

sText_NormanBattleRoomPrompt::
# 392 "data/text/factory_boss_texts.pory"
	.string "{PLAYER}!\p"
	.string "Let's get moving!\n"
	.string "I've been waiting for you!$"

sText_NormanBattleIntro::
# 399 "data/text/factory_boss_texts.pory"
	.string "Didn't expect to see me here, huh?\p"
	.string "Your old man still has a few tricks\n"
	.string "up his sleeve.\p"
	.string "You've always been a strong battler,\n"
	.string "but do you have the know-how\l"
	.string "to assemble a winning team?\p"
	.string "Show me everything you've learned!\n"
	.string "Don't hold back!$"

sText_NormanLastMonSlide::
# 413 "data/text/factory_boss_texts.pory"
	.string "You're no match for my {B_OPPONENT_MON1_NAME}!\n"
	.string "Let's end this!$"

sText_NormanLastMonLowHpSlide::
# 418 "data/text/factory_boss_texts.pory"
	.string "Well battled.\n"
	.string "Now finish it!$"

sText_NormanBattlePostWin::
# 423 "data/text/factory_boss_texts.pory"
	.string "Hah! That's the spirit.\p"
	.string "You fought with nerve and discipline.\n"
	.string "That's what wins tough matches.$"

sText_NormanBattleSpeechPlayerWon::
# 430 "data/text/factory_boss_texts.pory"
	.string "Wow! What a battle!\n"
	.string "Well fought.$"

sText_NormanBattleSpeechPlayerLost::
# 435 "data/text/factory_boss_texts.pory"
	.string "I'm disappointed, {PLAYER}...\n"
	.string "You could do far better!$"

sText_DebugBossName_Norman::
# 440 "data/text/factory_boss_texts.pory"
	.string "Norman$"

sText_WinonaPreBattleCall::
# 448 "data/text/factory_boss_texts.pory"
	.string "WINONA has a score to settle with you!$"

sText_WinonaBattleRoomPrompt::
# 452 "data/text/factory_boss_texts.pory"
	.string "Hey there, {PLAYER}!$"

sText_WinonaBattleIntro::
# 456 "data/text/factory_boss_texts.pory"
	.string "You will remember me as the one and\n"
	.string "only WINONA, LEADER of the FORTREE GYM!\p"
	.string "I have become one with bird POKéMON\n"
	.string "and have soared the skies!\p"
	.string "However grueling the battle, we will\n"
	.string "triumph with grace.\p"
	.string "A little birdie told me you became the\n"
	.string "CHAMPION, but in all my years, never\l"
	.string "have I seen a TRAINER command POKéMON\l"
	.string "with more grace than I.\p"
	.string "Now witness the elegant choreography\n"
	.string "of BIRD POKéMON and I!$"

sText_WinonaLastMonSlide::
# 475 "data/text/factory_boss_texts.pory"
	.string "Dance with me, {B_OPPONENT_MON1_NAME}!$"

sText_WinonaLastMonLowHpSlide::
# 479 "data/text/factory_boss_texts.pory"
	.string "Keep going, {B_OPPONENT_MON1_NAME}!$"

sText_WinonaBattlePostWin::
# 483 "data/text/factory_boss_texts.pory"
	.string "Though I fell to you, my wings\n"
	.string "will never break!$"

sText_WinonaBattleSpeechPlayerWon::
# 488 "data/text/factory_boss_texts.pory"
	.string "You truly are a graceful TRAINER.\n"
	.string "Not just a TRAINER, but a CHAMPION!$"

sText_WinonaBattleSpeechPlayerLost::
# 493 "data/text/factory_boss_texts.pory"
	.string "Our elegant dance is finished.\n"
	.string "Return, {B_OPPONENT_MON1_NAME}!$"

sText_DebugBossName_Winona::
# 498 "data/text/factory_boss_texts.pory"
	.string "Winona$"

sText_RedPreBattleCall::
# 505 "data/text/factory_boss_texts.pory"
	.string "A truly LEGENDARY TRAINER awaits!$"

sText_RedBattleRoomPrompt::
# 509 "data/text/factory_boss_texts.pory"
	.string "...$"

sText_RedBattleIntro::
# 513 "data/text/factory_boss_texts.pory"
	.string "...$"

sText_RedLastMonSlide::
# 517 "data/text/factory_boss_texts.pory"
	.string "...$"

sText_RedLastMonLowHpSlide::
# 521 "data/text/factory_boss_texts.pory"
	.string "...$"

sText_RedBattlePostWin::
# 525 "data/text/factory_boss_texts.pory"
	.string "...$"

sText_RedBattleSpeechPlayerWon::
# 529 "data/text/factory_boss_texts.pory"
	.string "...$"

sText_RedBattleSpeechPlayerLost::
# 533 "data/text/factory_boss_texts.pory"
	.string "...$"

sText_DebugBossName_Red::
# 537 "data/text/factory_boss_texts.pory"
	.string "Red$"
